config/routes.rb
YnSampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  
  default_scope order: 'microposts.created_at DESC'
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :microposts, dependent: :destroy
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  def feed
    # preliminary version
    Micropost.where("user_id = ?", id)
  end
  
  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: :destroy
  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end    
  end
  
  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  private 
    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id]) 
      redirect_to root_path if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # to show page
      sign_in user
      redirect_to user
    else
      # error and to signin
      flash.now[:error] = "Invalid login/password"
      render 'new'
    end
  end
  
  def destroy  
    sign_out 
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  before_filter :signed_new_create, only: [:new, :create]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome Aboard!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end  
  
  def update
    if @user.update_attributes(params[:user])    
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    unless current_user.id == params[:id].to_i 
      User.find(params[:id]).destroy   
      flash[:success] = "User destroyed."
    end
    redirect_to users_path
  end    
  
  private
  
  #  def signed_in_user
  #    redirect_to signin_path, notice: "Please sign in." unless signed_in?    
  #  end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end     
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end        
   
    def signed_new_create
      redirect_to(root_path) if signed_in?
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
    def sign_in(user)
       cookies.permanent[:remember_token] = user.remember_token
       current_user = user
    end  
    
    def signed_in?
      !current_user.nil?
    end
    
    def sign_out
      current_user = nil
      cookies.delete(:remember_token)
    end
    
    def current_user=(user)
      @current_user = user
    end  
    
    def current_user
      @current_user ||= user_from_remember_token
    end  
    
    def current_user? (user)
      user == current_user
    end
    
    def signed_in_user
      unless signed_in?
        #store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end
    
    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      clear_return_to
    end
    
    def store_location
      session[:return_to] = request.fullpath    
    end
    
    
    private
      
      def user_from_remember_token
        remember_token = cookies[:remember_token]
        User.find_by_remember_token(remember_token) unless remember_token.nil?                  
      end
   
      def clear_return_to
        session.delete(:return_to)
      end         
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      
      <%= content_tag(:div, value, :class => "alert alert-#{key}") %>             
      <% end %>
    
    
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
    <%= render "shared/micropost", object: micropost %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any?  %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error")  %>.
    </div>
    
    <ul>
    <% object.errors.full_messages.each do |msg|  %>
      <li>* <%= msg  %>  </li>
    <% end %>  
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  
  <%= render "shared/micropost", object: feed_item %>
</li>

app/views/shared/_micropost.html.erb
<!-- partial to render a micropost -->

  <span class="content"><%= wrap(object.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(object.created_at) %> ago.
  </span>
  <% if current_user?(object.user) %>
    <%= link_to "delete", object, method: :delete, 
              confirm: "You sure?", title: object.content %>      
  <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/_home_not_signed.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/_home_signed.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %> 
    </section>
    <section>
      <%= render 'shared/micropost_form' %> 
    </section>
  </aside> 
  <div class="span8">   
    <h3>Micropost Feed</h3> 
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development
	with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	This is the home page for the
	<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
      Get help on Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <%= render 'static_pages/home_signed'%>
<% else %>
  <%= render 'static_pages/home_not_signed'%>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
      
<%= f.label :name %>
<%= f.text_field :name %>
      
<%= f.label :email %>
<%= f.text_field :email %>
      
<%= f.label :password %>
<%= f.password_field :password %>
      
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
   <%= gravatar_for user, size: 52 %>
   <%= link_to user.name, user %>
   <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, conform: "You are sure?" %>
   <% end %>
</li> 

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>            
      <%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>                
    <% end %>
    
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>    
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %> 
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f|  %>
      <%= render 'fields', f: f %>        
      <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>      
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user, {:size => 150} %>
	      <%= @user.name %> 
      </h1>
    </section>
  </aside>
  
  <div class="span8"> 
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>) </h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>